### ISSUE TITLE
Add a CONTRIBUTING.MD file to the repo

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-kotlin#1]
As a developer/learner looking to contribute to this repo
I would like to see a `CONTRIBUTING.md` file 
So that I know what the contribution process is! 

## Task
+ [ ] Add a CONTRIBUTING.md file to the repo, pointing to https://github.com/dwyl/contributing, just like [this one](https://github.com/dwyl/hapi-auth-jwt2/blob/master/CONTRIBUTING.md)  🎉

**Comment by Rupeshiya** [comment]
hi @iteles 
I have already added the CONTRIBUTING.md.

**Comment by Rupeshiya** [comment]
Please check it @nelsonic .
I have also opened some issue ,so if you need some changes in that please share.
